services:
  - type: web
    name: otp-pro-inventory
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p instance/data
      touch instance/data/inventory.json
      touch instance/data/removals.json
      touch instance/data/activity.json
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        value: 100981239576129836054829374092873948623423667895